name: Demo workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: console_printing
        run: echo Hello, GitHub Actions!
      - name: few_lines_printing
        run: |
          echo First line!
          echo Second line!